FROM python:3.9

WORKDIR /app

RUN apt-get update && apt-get install -y portaudio19-dev python3-pyaudio

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "speech_recognition.py"]
